### ISSUE TITLE
Create unit test on cutflows

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#139]
```
CookTheBooks.py --files="user.mswiatlo:user.mswiatlo.370139.Gtt.DAOD_SUSY10.e4049_s2608_r6765_r6282_p2419_tag_13_xAOD_4_output_xAOD.root" --submitDir=TestCutflow --signalLeptonSelection="==0" --minMET=200 --dPhiMin=0.4 -yyyyyy --optimizationDump --badJetVeto --inputDQ2 -v -f condor > TestCutflow.log 2>&1 &
```

should produce

```
Preselection: 26270
MET>300: 23043
Nj >= 8: 18883
Nbj >= 4: 10159
mTbmin >= 160: 8257
meff >= 1200: 8201
```

**Comment by mswiatlo** [comment]
I might suggest that you change the running mode to “direct” for the test to make it quicker and non-batch dependent, since it’s just one small file.

Thanks!

On Oct 17, 2015, at 9:22 AM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

CookTheBooks.py --files="user.mswiatlo:user.mswiatlo.370139.Gtt.DAOD_SUSY10.e4049_s2608_r6765_r6282_p2419_tag_13_xAOD_4_output_xAOD.root" --submitDir=TestCutflow --signalLeptonSelection="==0" --minMET=200 --dPhiMin=0.4 -yyyyyy --optimizationDump --badJetVeto --inputDQ2 -v -f condor > TestCutflow.log 2>&1 &```

should produce

Preselection: 26270
MET>300: 23043
Nj >= 8: 18883
Nbj >= 4: 10159
mTbmin >= 160: 8257
meff >= 1200: 8201

**Comment by kratsg** [comment]
This will now be superseded by the https://github.com/discerning/papercuts/ team!
