### ISSUE TITLE
Fix the bins for jet multiplicity

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#26]
The bins are inappropriate and weird, and should be either

`11, -0.5, 10` or `21, -0.5, 20`.

**Comment by mswiatlo** [comment]
No reason not to go to 20 for a 1D histo, since memory isn’t a big concern and you can re-bin for display.

On Apr 22, 2015, at 9:27 AM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

The bins are inappropriate and weird, and should be either

11, -0.5, 10 or 21, -0.5, 20.
