### ISSUE TITLE
Missing SizeParameter in AntiKt4LCTopoJets

### ISSUE THREAD

**Issue by kratsg** [kratsg/TheAccountant#38]
All of the Akt4 jets in mc14_13TeV.110401.PowhegPythia_P2012_ttbar_nonallhad.merge.DAOD_SUSY4.e2928_s1982_s2008_r5787_r5853_p1862_tid05130501_00

do not have the SizeParameter set... however the Akt10Jets do.

Choices:
- default to using R=0.4 for Nsubjettiness calculations with or without a warning [can get incredibly verbose]
- skip jets that do not have SizeParameter set correctly (or at all) and return -99.9 for all calculations that need SizeParameter

**Comment by mswiatlo** [comment]
Why do we need n-subjettiness for a R=0.4 jet? This isn’t in the list of things we really need/want (at this stage of the analysis at least). We just need it for the R=1.0 jets, to get the top tags.

On May 26, 2015, at 7:40 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

All of the Akt4 jets in mc14_13TeV.110401.PowhegPythia_P2012_ttbar_nonallhad.merge.DAOD_SUSY4.e2928_s1982_s2008_r5787_r5853_p1862_tid05130501_00

do not have the SizeParameter set... however the Akt10Jets do. I'm going to default the Nsubjettiness calculation to an R=0.4 radius if they do not have a SizeParameter set. This might screw things up if other jets are missing a size parameter. Maybe it is easier if I just don't calculate subjettiness at all for the jets with no size parameter because that's weird...

**Comment by kratsg** [comment]
Well, one of the issues is that it is trying to compute for that size jet. The code will only compute it if the SizeParameter is a large value. If it is missing, it's screwing me up. For some reason, it's missing in _some_ jets of some events...

**Comment by kratsg** [comment]
I'm going to manually hard-code it for now to skip attempting to find the SizeParameter of jets that don't have it until I figure out what caused it to go missing.

**Comment by kratsg** [comment]
Oh, I figured out what was calling it. When I made the name change from `jets->largeRJets` and `bjets->jets` I forgot to update the topTag calls and they were top tagging on the wrong jets.
