### ISSUE TITLE
Fix mTb

### ISSUE THREAD

**Issue by AvivCukierman** [kratsg/TheAccountant#91]
mTb is NaN for most (but not all) events in the optimization tree

**Comment by mswiatlo** [comment]
What was the bug here out of curiosity?

On Aug 6, 2015, at 2:34 PM, Giordon Stark <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #91https://github.com/kratsg/TheAccountant/issues/91 via bd6d47bhttps://github.com/kratsg/TheAccountant/commit/bd6d47be857fc2600b66fb9a2dcfa96378effe61.

##

**Comment by kratsg** [comment]
`std::abs` to `std::fabs`
